### ISSUE TITLE
keyboard input not working (FF 38, Debian Linux)

### ISSUE THREAD

**Issue by utz82** [mborik/SAA1099Tracker#1]
As the title says, keyboard input isn't working on Firefox 38 und Debian Linux.

**Comment by mborik** [comment]
Sorry, but this is sadly very brief bugreport. I test every alpha-release in all major browsers and specially for FF I've solved lot of issues with keyboard handling, but now it works for me. Can you describe me steps to reproduce your issue? For example:
- Did you read documentation about hotkeys and controls (in up-right corner menu)?
- Did you have loaded a demosong or created some empty patterns and positions? (no song/data = nothing to control)
- Have you tried keyboard in edit mode (space)?
- What keyboard layout did you have selected while your test on your desktop?

**Comment by utz82** [comment]
Ah, I see - I created an empty pattern, but no new position. Problem solved! Thank you very much for the quick response, and the awesome tracker.
