### ISSUE TITLE
demosong Maaorava

### ISSUE THREAD

**Issue by shadowphiar** [mborik/SAA1099Tracker#2]
I'm happy for this to stay in here, but can you put "(MNEMOtech)" after the filename of demosong Maaorava - I believe this version originated as my conversion of a MOD file which I uploaded to sam-users a while back.
Also I think "Lizard" is by Ziutek.

**Comment by mborik** [comment]
Thank you for correction! I'm so glad if author contacts me with confession of authorship. This great songs which I promote to primary demosongs deserves it. ;)
Fixed in commit ccd413d18ccd6dc634b716767145cb44e193abc4

**Comment by shadowphiar** [comment]
Hi,

Thanks,  no problem.

Just out of interest, I was wondering how you initially performed the conversion from ProTracker's file format into this example? Do you have a script available somewhere to do this?

I see that SAA1099Tracker has space in the UI for import and export, but these were still disabled so far.


I was interested in the binary export because I've just discovered the archive of Sam music at http://zxart.ee/mobile/eng/music/top-100/sam-coupe/ - unfortunately it only contains ETracker music because that seems to be all that "zxplay" can understand (a program they use to produce MP3 and of files for web viewing). I considered trying to add support for ProTracker files but your STMF binary format seems like it might be a more flexible alternative. Have you had any thoughts along those lines?

Andrew

-- 
Sent from yet another low-energy ARM powered mobile device
Please excuse any imaginative autocorrect errors

**Comment by mborik** [comment]
All of that features are in development and **definitely** will be implemented... sooner or later.

Regarding to binary output, my brother Roman working on it and he already has some positive results (first working Z80 and i8080 player!), but it is still in WIP status. Description of our new, fully relocable, pointer based and byte-saving STMF binary format is [available here](https://github.com/mborik/SAA1099Tracker/blob/master/doc/export_data_format.txt) _(or in tracker's Help menu in the right upper corner)_ and it should be final draft. Now I have to write an optimizer and compiler into SAA1099Tracker to be able doing a binary data for export, optionally with player for both supported processor architectures. So, hold on! :wink: 

Regarding to ETracker or ProTracker II import, it was already implemented in predecessor of this project named [MIF85Tracker](https://sourceforge.net/p/mif85tracker/code/ci/master/tree/src/) where was a `FileFormatETrk.cpp` and `FileFormatPT2.cpp` importers which can grab binary source module of these old trackers and import into my tracker. Now I have to manualy "transpile" those C++ sources into JavaScript and integrate into SAA1099Tracker.

If I could have a little more time to all of that... :disappointed:
