### ISSUE TITLE
BUG: Compilation noise values sounds incorrect

### ISSUE THREAD

**Issue by stefandrissen** [mborik/SAA1099Tracker#26]
### 🐛 Describe the bug
Using [saa1099tracker.borik.net](https://saa1099tracker.borik.net/) (release 2.01), I imported the demo Turrican song and then exported it to Z80 SAM Coupé including player. The white noise in the second pattern sounds too simple in [SimCoupe](https://github.com/simonowen/simcoupe/releases) versus browser playback.

See [turrican.zip](https://github.com/mborik/SAA1099Tracker/files/10190596/turrican.zip), the disk image that will autoboot in SimCoupe.

The export function is **VERY COOL** BTW.

I have also created an [oscilloscope video](https://youtu.be/ZZA-ZQED-94) of the SimCoupe output.

**Comment by mborik** [comment]
Thank you Stefan. You can't imagine how much I appreciate your effort and support. Finally, I'm not alone on all this. 🙏 
Yes, there is definitely invalid interpretation of noise value. Those players are made by my older brother, so he'll do the investigation. 👍  It could be maybe just discrepancy between i8080 and z80 implementation... we will see.
Also, I discovered a malfunction in optimizer of compiler: The Turrican compilation is way more lengthy that it should be. 🤭

**Comment by mborik** [comment]
✅  Deployed on server in v2.0.3

**Comment by stefandrissen** [comment]
Hi Martin,

It sounds better, but it still sounds different to me (the second white noise part):
[turrican.203.dsk.zip](https://github.com/mborik/SAA1099Tracker/files/10254163/turrican.203.dsk.zip)

**Comment by mborik** [comment]
Oh, I see! You have compiled my latest version of Turrican, where I've prepared command `A` (volume slide) for my brother to test his implementation in player. _(Now it sounds more like Amiga original ☺️)_
