### ISSUE TITLE
BUG: Songs made in 2021 and earlier fail to open

### ISSUE THREAD

**Issue by Camtronic16** [mborik/SAA1099Tracker#36]
All of the old songs I've made on an older version of SAA1099Tracker no longer open at all, with the newest file being from the 5th of January 2021. 
In addition, I get an error: 
`Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded contains characters outside of the Latin1 range.`

I looked in the Local Storage via Google Chrome's DevTools and noticed that the `stmf***-dat` keys contain a bunch of weird gibberish characters, mostly squares, Chinese characters and other miscellaneous symbols. I compared it to a much newer song file and it looks to be Base64 encoded instead. 

I tried converting one of the old files to Base64 to no avail, getting an `incorrect header check` error instead. I also have no idea where the Local Storage is stored on my computer so that I could back them up elsewhere.

### 🖥 Desktop
 - **OS:**  Windows 10
 - **Browser:** Chrome 
 - **Version:** 109.0.5414.74 (Official Build)

**Comment by mborik** [comment]
Closing support ticket after month without respond.
